### ISSUE TITLE
Issue with zksync-ethers.js version 6: Blockage on Usage, Works with Version 5

### ISSUE THREAD

**Issue by Cryptostart1** [zksync-sdk/zksync-ethers#92]
🐛 Bug Report for zksync-ethers JavaScript SDK

📝 Description
I wanted to bring to your attention an issue I encountered while using zksync-ethers.js version 6. It appears that there is a compatibility issue or a bug with this version, as I experienced errors when trying to run my code. Specifically, I was unable to retrieve block information using zksync-ethers.js version 6, whereas the same code worked perfectly fine with version 5.

To resolve this issue, I downgraded to zksync-ethers.js version 5, and the problem was resolved. I was able to successfully retrieve the required block information without any errors.

There is an issue with the zksync-ethers JavaScript SDK version 6 where certain functionalities do not work as expected.

🔄 Reproduction Steps
Install zksync-ethers version 6.
Attempt to perform certain operations, such as retrieving latest block number

```
const { Provider, utils, types } = require("zksync-ethers");
const { ethers } = require("ethers");

async function main() {
    const provider = Provider.getDefaultProvider(types.Network.Sepolia);
    const ethProvider = ethers.getDefaultProvider("sepolia");

    // Get the network
    const network = await provider.getNetwork();
    console.log(`Network: ${JSON.stringify(network)}`);

    // Get the latest block number
    const blockNumber = await provider.getBlockNumber();
    console.log(`Block number: ${blockNumber}`);


}

main().catch(console.error);
```
Observe the error or unexpected behavior.

🤔 Expected Behavior
I expected the SDK to function without errors and provide accurate information regarding blocks.

😯 Current Behavior
The SDK throws errors and does not retrieve block information correctly.

🖥️ Environment
Node version: 18.16.1
Operating System & Version: macOS
Other relevant environment details:

📋 Additional Context
This issue was not present in zksync-ethers version 5, suggesting a regression in functionality with the latest version.

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

```
node essai.js
/Users/michel/botcrevic/node_modules/zksync-ethers/build/types.js:58
class TransactionResponse extends ethers_1.ethers.TransactionResponse {
                                                  ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/michel/botcrevic/node_modules/zksync-ethers/build/types.js:58:51)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/michel/botcrevic/node_modules/zksync-ethers/build/utils.js:22:17)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

Node.js v18.16.1
```

**Comment by danijelTxFusion** [comment]
Do you use one of the latest versions of SDK? I managed to fetch block and number with version `v6.6.0` and `v6.5.0`:

```ts
import { Provider, types, utils } from "zksync-ethers";

const provider = Provider.getDefaultProvider(types.Network.Sepolia);

async function main() {
    console.log(`Block number: ${await provider.getBlockNumber()}`);
    const block = await provider.getBlock("latest", true);
    console.log(`Block: ${utils.toJSON(block)}`);;
}

main()
    .then()
    .catch((error) => {
        console.log(`Error: ${error}`);
    });

```

output:
```
Block number: 1379704
Block: {"_type":"Block","baseFeePerGas":"100000000","difficulty":"0","extraData":"0x","gasLimit":"4294967295","gasUsed":"335821","hash":"0x61bff05d816eb38839a9636a0bb6eddbea3e4101dbed6d7cda4ffb46de6b64c5","miner":"0x0000000000000000000000000000000000000000","nonce":"0x0000000000000000","number":1379704,"parentHash":"0x51f5f524fd28499b7a395f64184b060ced8fb208abfd2321da4bd55c375f58fd","timestamp":1711649800,"transactions":["0xf7ad0f6597c14bdd0767c34ed1e6c016ba7780fed1fbb12b8ace424e013e9e7c"]}
```

**Comment by jyap808** [comment]
Replicated the same issue with zksync-ethers 6.16.0 and Node 22.10.0:
```
% node essai.js
/home/julian/go/src/github.com/jyap808/hyperlane-hack1/node_modules/zksync-ethers/build/types.js:58
class TransactionResponse extends ethers_1.ethers.TransactionResponse {
                                                  ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/julian/go/src/github.com/jyap808/hyperlane-hack1/node_modules/zksync-ethers/build/types.js:58:51)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/home/julian/go/src/github.com/jyap808/hyperlane-hack1/node_modules/zksync-ethers/build/utils.js:23:17)

Node.js v22.10.0
```

Switching to an older zksync-ethers 5.10.0 worked fine:
```
% node essai.js
Network: {"chainId":300,"name":"unknown"}
Block number: 4596171
```
